### ISSUE TITLE
Inline code block inside container directive causes parse error.

### ISSUE THREAD

**Issue by Corvimae** [micromark/micromark-extension-directive#6] opened 2021-01-04 18:10 UTC
### Subject of the issue
An inline code block inside a container directive causes the parser to fail.

```
:::card
The formula used is `stat / 255`.
:::
```
```
TypeError: undefined has no properties
    childrenToText directiveConverter.ts:11
    childrenToText directiveConverter.ts:11
    childrenToText directiveConverter.ts:11
    onDirective directiveConverter.ts:28
    overload index.js:27
    visit index.js:56
    visit index.js:67
    visitParents index.js:29
    visit index.js:22
    transform directiveConverter.ts:18
    wrapped wrap.js:25
    next index.js:57
    run index.js:31
    executor index.js:305
    run index.js:302
    pipelineRun index.js:27
    wrapped wrap.js:25
    next index.js:57
    done wrap.js:55
    then wrap.js:62
    wrapped wrap.js:45
    next index.js:57
    run index.js:31
    executor index.js:375
    process index.js:370
    processSync index.js:399
```
### Your environment

*   **OS**: macOS Big Sur
*   **Packages**:
 ```
├─ micromark-extension-directive@1.1.2
│  ├─ micromark@~2.11.0
```
*   **Env**: node `v15.5.0`, yarn `1.22.5`

### Steps to reproduce

See subject.

### Expected behavior

The container directive renders correctly.

### Actual behavior

Parsing fails.

**Comment by ChristianMurphy** [comment] 2021-01-04 18:12
this looks like an accidental duplicate of #5?
Closing in favor of the first.

**Closed by ChristianMurphy** 2021-01-04 18:12 UTC
Labels: 🐛 type/bug, 🔍 status/open

**Comment by Corvimae** [comment] 2021-01-04 18:14
Oh weird. Github gave me a 404 the first time so I assumed it failed, my bad 🤦‍♀️ .
